### ISSUE TITLE
Job fails on GitlabCI

### ISSUE THREAD

**Issue by jeanmatthieud** [cirruslabs/docker-images-flutter#26]
Hi,

I used your image a lot. However, today, my builds are failing.

```bash
Running with gitlab-ci-multi-runner 9.5.1 (96b34cc)
  on gitlab (8c990da3)
Using Docker executor with image cirrusci/flutter:v1.7.8-hotfix.4 ...
Using docker image sha256:abe37c5d1967d5bffcbbbf7adada8a864010a050a0067931a9ef14c72b23b59c for predefined container...
Pulling docker image cirrusci/flutter:v1.7.8-hotfix.4 ...
Using docker image cirrusci/flutter:v1.7.8-hotfix.4 ID=sha256:7ceafaabf9fb071a4a589736baeeacde88cfdb2a49c2a0c4a578ca5df1ecf803 for build container...
Running on runner-8c990da3-project-129-concurrent-0 via gitlab...
Fetching changes...
Removing .flutter-plugins
Removing .packages
Removing android/.gradle/
Removing android/app/src/main/java/io/
Removing android/gradle/wrapper/gradle-wrapper.jar
Removing android/gradlew
Removing android/gradlew.bat
Removing android/local.properties
Removing build/
Removing ios/Flutter/Generated.xcconfig
Removing ios/Runner/GeneratedPluginRegistrant.h
Removing ios/Runner/GeneratedPluginRegistrant.m
Removing pubspec.lock
HEAD is now at d5f4c59 Specify flutter docker image version
From -snip-
 * [new tag]         v1.2.1     -> v1.2.1
Checking out d5f4c594 as v1.2.1...
Skipping Git submodules setup
$ flutter build appbundle --build-name ${CI_COMMIT_TAG:1} --build-number $CI_BUILD_ID
Running "flutter pub get" in -snip-...                  12.8s
Initializing gradle...                                              9.8s
Resolving dependencies...                                          66.3s
Running Gradle task 'bundleRelease'...                          
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

ProcessException: 
  Command: /usr/bin/git log -n 1 --pretty=format:%H
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:343:48)
#5      runSync (package:flutter_tools/src/base/process.dart:315:10)
#6      _runGit (package:flutter_tools/src/version.dart:532:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:26)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:81:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:113:23)
#14     FlutterVersion.instance (package:flutter_tools/src/version.dart:183:49)
#15     new Usage (package:flutter_tools/src/usage.dart:60:58)
#16     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:101:20)
#17     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#18     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#19     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#20     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#21     AppContext.get (package:flutter_tools/src/base/context.dart:113:23)
#22     Usage.instance (package:flutter_tools/src/usage.dart:84:40)
#23     flutterUsage (package:flutter_tools/src/usage.dart:54:33)
#24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:367:11)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#31     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#32     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#33     new Future.sync (dart:async/future.dart:224:31)
#34     CommandRunner.run (package:args/command_runner.dart:112:14)
#35     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#36     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1500:12)
#41     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#42     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _runZoned (dart:async/zone.dart:1516:10)
#46     runZoned (dart:async/zone.dart:1463:12)
#47     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#48     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#49     run (package:flutter_tools/runner.dart:51:10)
#50     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#51     main (file:///home/cirrus/sdks/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#52     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

ProcessException: OS error message was a not a utf8 string.
  Command: /usr/bin/git log -n 1 --pretty=format:%H
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:343:48)
#5      runSync (package:flutter_tools/src/base/process.dart:315:10)
#6      _runGit (package:flutter_tools/src/version.dart:532:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:26)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:81:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:183:49)
#14     new Usage (package:flutter_tools/src/usage.dart:60:58)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:101:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#20     Usage.instance (package:flutter_tools/src/usage.dart:84:40)
#21     flutterUsage (package:flutter_tools/src/usage.dart:54:33)
#22     _exit (package:flutter_tools/runner.dart:206:7)
<asynchronous suspension>
#23     _handleToolError (package:flutter_tools/runner.dart:110:14)
<asynchronous suspension>
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:65:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#39     main (file:///home/cirrus/sdks/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Unhandled exception:
ProcessException: ls/runner.dart:65:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#39     main (file:///home/cirrus/sdks/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

  Command: /usr/bin/git log -n 1 --pretty=format:%H
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:343:48)
#5      runSync (package:flutter_tools/src/base/process.dart:315:10)
#6      _runGit (package:flutter_tools/src/version.dart:532:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:26)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:81:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:183:49)
#14     new Usage (package:flutter_tools/src/usage.dart:60:58)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:101:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#17     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:281:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#20     Usage.instance (package:flutter_tools/src/usage.dart:84:40)
#21     flutterUsage (package:flutter_tools/src/usage.dart:54:33)
#22     _exit (package:flutter_tools/runner.dart:206:7)
<asynchronous suspension>
#23     _handleToolError (package:flutter_tools/runner.dart:110:14)
<asynchronous suspension>
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:69:13)
<asynchronous suspension>
#25     _rootRunBinary (dart:async/zone.dart:1148:13)
#26     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#27     runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
#28     _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#29     Future._propagateToListeners (dart:async/future_impl.dart:589:16)
#30     Future._completeError (dart:async/future_impl.dart:491:5)
#31     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#32     _Completer.completeError (dart:async/future_impl.dart:27:5)
#33     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:51:10)
#48     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#49     main (file:///home/cirrus/sdks/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Running Gradle task 'bundleRelease'...                             16.7s
Gradle task bundleRelease failed with exit code 1
ERROR: Job failed: exit code 1
```

**Comment by fkorotkov** [comment]
It seems like a gradle problem of handling emojis in environment variables.

> OS error message was a not a utf8 string.

Does you commit's message for that build contain emojis?

Links: https://github.com/flutter/flutter/issues/24935 and https://github.com/flutter/flutter/issues/28151

**Comment by jeanmatthieud** [comment]
No, I don't.
I rebooted the GitLab instance, and now I have another error:

```bash
Running with gitlab-ci-multi-runner 9.5.1 (96b34cc)
  on gitlab (8c990da3)
Using Docker executor with image cirrusci/flutter:v1.7.8-hotfix.4 ...
Using docker image sha256:ebae506da33c0fa0e4863376e3a0770f4db6f16b0d25f24de95bb2930db53328 for predefined container...
Pulling docker image cirrusci/flutter:v1.7.8-hotfix.4 ...
Using docker image cirrusci/flutter:v1.7.8-hotfix.4 ID=sha256:7ceafaabf9fb071a4a589736baeeacde88cfdb2a49c2a0c4a578ca5df1ecf803 for build container...
Running on runner-8c990da3-project-129-concurrent-0 via gitlab...
Cloning repository...
Cloning into '/mnt/data/gitlab/runner/breizhstar/breizhstar-mobile'...
Checking out d5f4c594 as v1.2.1...
Skipping Git submodules setup
$ flutter build appbundle --build-name ${CI_COMMIT_TAG:1} --build-number $CI_BUILD_ID
Running "flutter pub get" in breizhstar-mobile...                  12.8s
Initializing gradle...                                              9.2s
Resolving dependencies...                                          63.5s
Running Gradle task 'bundleRelease'...                          
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

../../third_party/dart/runtime/vm/zone.cc: 72: error: Out of memory.
version=2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "linux_x64"
thread=407, isolate=main(0x18ddd10)

  pc 0x000000000156b64c fp 0x00007faf49c3d8a0 /home/cirrus/sdks/flutter/bin/cache/dart-sdk/bin/dart+0x136b64c
-- End of DumpStackTrace


===== CRASH =====
si_signo=Bus error(7), si_code=2, si_addr=0x7f8cf9e051e0
version=2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "linux_x64"












thread=393, isolate=main(0x18b9c60)
Stack dump aborted because InitialRegisterCheck failed.

/home/cirrus/sdks/flutter/bin/flutter: line 183:   390 Aborted                 (core dumped) "$DART" --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
Running Gradle task 'bundleRelease'...                             23.4s
Gradle task bundleRelease failed with exit code 1
ERROR: Job failed: exit code 1
```

**Comment by fkorotkov** [comment]
BTW I did bump the stable version from `v1.7.8-hotfix.3` to `v1.7.8-hotfix.4` in #25. Could you please check logs of the last successful build and check the tag it used?

**Comment by jeanmatthieud** [comment]
Thanks for your time.
The last successful build was already in flutter `v1.7.8-hotfix.4`. Maybe it's just my device which is not enough powerful...

```bash
Running with gitlab-ci-multi-runner 9.5.1 (96b34cc)
  on gitlab (8c990da3)
Using Docker executor with image cirrusci/flutter ...
Using docker image sha256:7f54b9368b7c51ea7cf8e84c6a8885c3143ffe5a7f14ac5bb06c49a22d9b25fe for predefined container...
Pulling docker image cirrusci/flutter ...
Using docker image cirrusci/flutter ID=sha256:702468825c3b2d268fa8d86484cd2aa28670deb2db33c5ed1500760c3d712f7f for build container...
Running on runner-8c990da3-project-129-concurrent-0 via gitlab...
Cloning repository...
Cloning into '-snip-'...
Checking out 45eb4066 as master...
Skipping Git submodules setup
$ flutter channel stable
Switching to flutter channel 'stable'...
git: From https://github.com/flutter/flutter
git:    30eec11e7..ef146f63b  master     -> origin/master
git: Switched to a new branch 'stable'
git: Branch stable set up to track remote branch stable from origin.
$ flutter upgrade
Upgrading Flutter from /home/cirrus/sdks/flutter...
Updating d51fd86cd..20e59316b
 19 files changed, 61 insertions(+), 33 deletions(-)

Upgrading engine...

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (11 days ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

Running "flutter pub upgrade" in -snip-...              15.7s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
$ flutter build apk --build-name "0.0.$CI_BUILD_ID" --build-number $CI_BUILD_ID
```

**Comment by fkorotkov** [comment]
Interesting! Yes, there is this error:

> dart/runtime/vm/zone.cc: 72: error: Out of memory.

How much power does your GitLab instance has?

**Comment by jeanmatthieud** [comment]
It's a 4 core / 4 Gb cloud server runned by Scaleway (START1-M - not sold anymore)

**Comment by fkorotkov** [comment]
Not a lot indeed! Doesn't seem like the issue is with the image since you had successful builds with the latest tag. You can try to monitor the instance's CPU and memory usage to verify it's the lack of resources issue.

**Comment by jeanmatthieud** [comment]
Thanks for your help.
I created a runner from a local mac mini which is always on for compiling xcode projects.
