### ISSUE TITLE
Couldn't find a valid ICU package installed on the system

### ISSUE THREAD

**Issue by benNeuro** [cirruslabs/docker-images-flutter#329]
As of version 3.22.0 my builds are failing with following error:
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at Unity.Options.OptionsParser.LoadOptionTypesFromAssembly(System.Reflection.Assembly, Boolean, System.Func`2<System.Reflection.AssemblyName,Boolean>, System.Func`2<System.Reflection.Assembly,System.Type[]>)
   at il2cpp.Il2CppOptionParser.ParseArguments(System.String[], Boolean ByRef, il2cpp.ExitCode ByRef, Unity.IL2CPP.Common.RuntimePlatform ByRef, Unity.IL2CPP.Building.BuildingOptions ByRef, System.String ByRef)
   at il2cpp.Program.Run(System.String[], Boolean, Boolean)
   at il2cpp.Program.Main(System.String[])
```

Everything works as expected with version 3.19.6

Some additional details:
- Our project uses an embedded Unity player [using this package](https://pub.dev/packages/flutter_unity_widget). The error seems to be related to that
- Adding the environment variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` fixes this, but I'm worried about [potential issues](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md)

**Comment by bartekpacia** [comment]
Can you provide a reproducible example?
